apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /app/logs/travel-app.log
        Tag               travel.logs
        Refresh_Interval  5
        Mem_Buf_Limit     5MB

    [OUTPUT]
        Name              s3
        Match             travel.logs
        bucket            travel-app-logs-dmlguq1537
        region            ap-northeast-2
        compression       gzip
        s3_key_format     /travel.logs/%Y/%m/%d/%H/%M/%S/$UUID.gz
        total_file_size   1M
        upload_timeout    1m
