# 1. Monitoring (자원을 많이 먹지만 4G 환경에선 1.2G 정도로 타협)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "700m"
    requests.memory: "1.5Gi"
    limits.cpu: "2800m"
    limits.memory: "2Gi"

---
# 2. ArgoCD (103% 문제를 해결하면서도 4G에 맞게 최적화)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: argocd
spec:
  hard:
    requests.memory: "400Mi"
    limits.memory: "600Mi" 
---
# 3. Ingress-Nginx (관문이므로 최소한의 방어선 유지)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: ingress-nginx
spec:
  hard:
    requests.memory: "200Mi"
    limits.memory: "200Mi" #  (현재 사용량이 매우 적으므로 충분함)
---
# 4. Kube-System (시스템 필수 요소)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: kube-system
spec:
  hard:
    requests.memory: "300Mi"
    limits.memory: "4000Mi" 
---
# 5. Default (사용자 앱 - Travel-App)
# 가장 중요한 서비스이므로 여기서 자원을 최대한 확보합니다.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: default
spec:
  hard:
    requests.memory: "4000Mi"
    limits.memory: "5Gi"

---
# 6. logging (loki 가 깔려있는 네임스페이스)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: logging-quota
  namespace: logging
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "800Mi"
    limits.cpu: "1000m"
    limits.memory: "2Gi"
