#  PVC (실제 1GB 용량 빌리기)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: travel-image-efs-pvc  # 새로운 EFS용 PVC 이름
spec:
  accessModes:
    - ReadWriteMany           # ⭐ EFS의 장점! 여러 노드 동시 접속
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  volumeName: travel-image-efs-pv # ⭐ 위에서 만든 PV 이름과 연결
