# 1. 스토리지 클래스 (어떤 드라이버를 쓸지 정의)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-079f6e280570a31f9  # ⭐ 여기에 복사한 EFS ID를 꼭 넣어주세요!
  directoryPerms: "700"


      
